unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on
set -g history-limit 50000
set -g set-clipboard on
set -g allow-passthrough on
set -g renumber-windows on

set -g status-style "bg=#{?client_prefix,colour208,colour235},fg=white"

set -g pane-border-status top
set -g pane-border-format "#[align=right]#{?pane_active,#[bg=colour39]#[fg=black]#[bold],#[bg=colour238]#[fg=colour250]} #{pane_index}: #{pane_title} "
set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=colour39"

setw -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind x kill-pane

bind h display-popup -E -w 80% -h 80% "less $HOME/develop/tmux-config/cheatsheet.md"
bind T command-prompt -p "pane title:" "select-pane -T '%%'"
